"""macOS ``.app`` bundle generator.

Wraps ``lang-view`` in a minimal ``.app`` so macOS TCC (Screen Recording,
Accessibility) can identify the agent reliably. Without a bundle, macOS
tracks permissions per-binary against an unsigned ``python`` interpreter
which is unreliable when the process is spawned by launchd.

The bundle is intentionally tiny: ``Info.plist`` plus a single bash
launcher in ``Contents/MacOS`` that exec's ``python -m lang_view "$@"``.
The launchd agent then references that launcher in ``ProgramArguments``
and inherits the bundle's TCC identity.

The plist generator is pure and fully tested; ``write_app_bundle``
shells out only insofar as it sets the executable bit on the launcher
script (``chmod``, no subprocesses). Ad-hoc signing and Launch Services
registration are separate, best-effort helpers (``codesign_bundle``,
``lsregister_bundle``) that the CLI runs after the bundle is written.
"""

from __future__ import annotations

import logging
import plistlib
import stat
import subprocess
from pathlib import Path

log = logging.getLogger(__name__)

DEFAULT_BUNDLE_ID = "ai.lang-view"
DEFAULT_BUNDLE_NAME = "Lang-View"
DEFAULT_EXECUTABLE_NAME = "lang-view"


def render_info_plist(
    *,
    bundle_id: str = DEFAULT_BUNDLE_ID,
    bundle_name: str = DEFAULT_BUNDLE_NAME,
    executable_name: str = DEFAULT_EXECUTABLE_NAME,
    version: str = "0.1.0",
    lsui_element: bool = True,
) -> bytes:
    plist = {
        "CFBundleIdentifier": bundle_id,
        "CFBundleName": bundle_name,
        "CFBundleDisplayName": bundle_name,
        "CFBundleExecutable": executable_name,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "LSMinimumSystemVersion": "10.15",
        # LSUIElement=true means the bundle has no Dock icon and doesn't
        # appear in the App Switcher. The watch loop is a background
        # agent; the menubar uses its own status item via rumps.
        "LSUIElement": bool(lsui_element),
        "NSHighResolutionCapable": True,
    }
    return plistlib.dumps(plist)


def _quote_for_bash(s: str) -> str:
    if not s:
        return "''"
    if all(c.isalnum() or c in "_-./=" for c in s):
        return s
    return "'" + s.replace("'", "'\\''") + "'"


def render_launcher_script(python_executable) -> str:
    """Return a bash script that runs ``python -m lang_view "$@"``.

    The launcher is the bundle's CFBundleExecutable. It receives args
    from launchd's ``ProgramArguments`` (everything after [0]) and
    forwards them verbatim to the watch / menubar subcommand.

    We do **not** use ``exec``: the bash process must stay alive as
    the parent so macOS TCC attributes Screen Recording to the bundle
    rather than the unsigned ``python`` binary. ``trap`` forwards
    SIGTERM/SIGINT to the python child so launchd's bootout still
    cleans up cleanly.
    """
    py = _quote_for_bash(str(python_executable))
    return (
        "#!/bin/bash\n"
        '# Generated by lang-view package-app. Do not edit by hand;\n'
        '# re-run `lang-view package-app` to regenerate.\n'
        '# Parent stays alive so macOS attributes TCC to this .app bundle.\n'
        f'{py} -m lang_view "$@" &\n'
        'child=$!\n'
        'trap "kill -TERM $child 2>/dev/null" TERM INT\n'
        'wait $child\n'
    )


def write_app_bundle(
    dest,
    *,
    python_executable,
    bundle_id: str = DEFAULT_BUNDLE_ID,
    bundle_name: str = DEFAULT_BUNDLE_NAME,
    executable_name: str = DEFAULT_EXECUTABLE_NAME,
    lsui_element: bool = True,
):
    """Create a ``.app`` bundle at ``dest``. Returns the dest path.

    Idempotent: re-running on an existing bundle overwrites the plist
    and launcher in place.
    """
    dest = Path(dest)
    contents = dest / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    macos.mkdir(parents=True, exist_ok=True)
    resources.mkdir(parents=True, exist_ok=True)

    (contents / "Info.plist").write_bytes(
        render_info_plist(
            bundle_id=bundle_id,
            bundle_name=bundle_name,
            executable_name=executable_name,
            lsui_element=lsui_element,
        )
    )

    launcher = macos / executable_name
    launcher.write_text(render_launcher_script(python_executable))
    mode = launcher.stat().st_mode
    launcher.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Make a top-level "PkgInfo" file. macOS Finder uses it to identify
    # the bundle as an APPL of type "????".
    (contents / "PkgInfo").write_text("APPL????")

    return dest


_LSREGISTER = (
    "/System/Library/Frameworks/CoreServices.framework"
    "/Frameworks/LaunchServices.framework/Support/lsregister"
)


def _default_runner(cmd):
    return subprocess.run(cmd, capture_output=True, text=True, timeout=30, check=False)


def codesign_bundle(dest, *, runner=None) -> bool:
    """Ad-hoc sign the bundle so its TCC identity is pinned to a code hash.

    Without a signature, macOS may invalidate granted permissions when
    files inside the bundle change — the whole point of the bundle is
    a stable identity, so signing is what makes it stable.

    Best-effort: returns True on success, False (with a logged warning)
    on failure. Tests inject ``runner`` to avoid shelling out.
    """
    runner = runner or _default_runner
    cmd = ["codesign", "--force", "--deep", "--sign", "-", str(dest)]
    try:
        result = runner(cmd)
    except (FileNotFoundError, subprocess.SubprocessError) as e:
        log.warning("codesign not available or failed to launch: %s", e)
        return False
    if result.returncode != 0:
        log.warning("codesign failed (rc=%d): %s",
                    result.returncode, (result.stderr or result.stdout or "").strip())
        return False
    return True


def lsregister_bundle(dest, *, runner=None) -> bool:
    """Register the bundle with Launch Services so ``open -a`` finds it.

    Without registration, ``open -a "Lang-View"`` may fail to resolve the
    bundle, which the ``chrome-permission-test`` flow relies on to
    provoke macOS Automation prompts from the bundle's identity.

    Best-effort: returns True on success, False on failure.
    """
    runner = runner or _default_runner
    cmd = [_LSREGISTER, "-f", str(dest)]
    try:
        result = runner(cmd)
    except (FileNotFoundError, subprocess.SubprocessError) as e:
        log.warning("lsregister not available or failed to launch: %s", e)
        return False
    if result.returncode != 0:
        log.warning("lsregister failed (rc=%d): %s",
                    result.returncode, (result.stderr or result.stdout or "").strip())
        return False
    return True


def default_bundle_path(name: str = DEFAULT_BUNDLE_NAME) -> Path:
    return Path.home() / "Applications" / f"{name}.app"


def bundle_executable(bundle_path) -> Path:
    """Return the launcher script path inside ``bundle_path``."""
    p = Path(bundle_path)
    info = plistlib.loads((p / "Contents" / "Info.plist").read_bytes())
    exe = info.get("CFBundleExecutable") or DEFAULT_EXECUTABLE_NAME
    return p / "Contents" / "MacOS" / exe
